import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  team,
  dashboard,
}: Readonly<{
  children: React.ReactNode;
  team: React.ReactNode;
  dashboard: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="mx-auto w-[700px]">
          <section className="py-6">{children}</section>
          <section className="flex gap-6">
            {team} {dashboard}
          </section>
        </main>
      </body>
    </html>
  );
}
